load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

CXX_COMMON = [
    "-Werror",
    "-Wno-reorder",
    "-Wcast-align",
    "-Wcast-qual",
    "-Wconversion",
    "-Wdisabled-optimization",
    "-Wextra",
    "-Wfloat-equal",
    "-Wformat=2",
    "-Wformat-nonliteral",
    "-Wformat-security",
    "-Wformat-y2k",
    "-Wimport",
    "-Winit-self",
    "-Winvalid-pch",
    "-Wlong-long",
    "-Wmissing-field-initializers",
    "-Wmissing-format-attribute",
    "-Wno-aggregate-return",
    "-Wno-padded",
    "-Wno-switch-enum",
    "-Wno-unused-parameter",
    "-Wpacked",
    "-Wpointer-arith",
    "-Wredundant-decls",
    "-Wstack-protector",
    "-Wstrict-aliasing=3",
    "-Wswitch",
    "-Wswitch-default",
    "-Wunreachable-code",
    "-Wunused",
    "-Wvariadic-macros",
    "-Wno-switch-default",
    "-Wno-long-long",
    "-Wno-redundant-decls",
    "-Wno-implicit-fallthrough",
    "-Wno-error=class-memaccess",
    "-DNDEBUG",
]

filegroup(
    name = "swss_lua_scripts",
    srcs = glob(["*.lua"]),
)

cc_library(
    name = "orch_common",
    srcs = [
        "orch.cpp",
        "request_parser.cpp",
        "response_publisher.cpp",
    ] + ["//fpmsyncd:fpmsyncd.h"],
    hdrs = glob(["**/*.h"]),
    cxxopts = CXX_COMMON + [
        "-Wno-write-strings",
        "-Wno-error=overloaded-virtual",
        "-std=c++17",
    ],
    includes = [
        ".",
        "cbf",
        "debug_counter",
        "flex_counter",
        "high_frequency_telemetry",
        "nhg",
        "pbh",
        "port",
        "switch",
    ],
    deps = [
        "//lib:libswss",
        "//warmrestart",
        "@libnl3//:libnl_3",
        "@libnl3//:libnl_route_3",
        "@sai//meta:saimetadata",
        "@sonic_sairedis//meta:saimeta",
        "@sonic-swss-common//:swsscommon",
        "@swss_apt_deps//libhiredis-dev:libhiredis",
        "@swss_apt_deps//libzmq3-dev:libzmq3",
        "@sonic_rules//system_libs:pthread",
    ],
)

exports_files(["macsecpost.cpp"])

orchagent_SOURCES = [
    "main.cpp",
    "orchdaemon.cpp",
    "notifications.cpp",
    "nhgorch.cpp",
    "nhgbase.cpp",
    "cbf/cbfnhgorch.cpp",
    "cbf/nhgmaporch.cpp",
    "routeorch.cpp",
    "mplsrouteorch.cpp",
    "neighorch.cpp",
    "intfsorch.cpp",
    "evpnmhorch.cpp",
    "l2nhgorch.cpp",
    "port/port_capabilities.cpp",
    "port/porthlpr.cpp",
    "portsorch.cpp",
    "fabricportsorch.cpp",
    "fgnhgorch.cpp",
    "copporch.cpp",
    "tunneldecaporch.cpp",
    "qosorch.cpp",
    "buffer/bufferhelper.cpp",
    "bufferorch.cpp",
    "mirrororch.cpp",
    "fdborch.cpp",
    "macmoveguard.cpp",
    "aclorch.cpp",
    "pbh/pbhcap.cpp",
    "pbh/pbhcnt.cpp",
    "pbh/pbhmgr.cpp",
    "pbh/pbhrule.cpp",
    "pbhorch.cpp",
    "saihelper.cpp",
    "saiattr.cpp",
    "switch/switch_capabilities.cpp",
    "switch/switch_helper.cpp",
    "switch/trimming/capabilities.cpp",
    "switch/trimming/helper.cpp",
    "switchorch.cpp",
    "pfcwdorch.cpp",
    "pfcactionhandler.cpp",
    "crmorch.cpp",
    "vrforch.cpp",
    "countercheckorch.cpp",
    "vxlanorch.cpp",
    "tunneltermhelper.cpp",
    "vnetorch.cpp",
    "dtelorch.cpp",
    "flexcounterorch.cpp",
    "watermarkorch.cpp",
    "notificationconsumerstatsorch.cpp",
    "policerorch.cpp",
    "sfloworch.cpp",
    "chassisorch.cpp",
    "debugcounterorch.cpp",
    "natorch.cpp",
    "mlagorch.cpp",
    "isolationgrouporch.cpp",
    "muxorch.cpp",
    "macsecorch.cpp",
    "lagid.cpp",
    "bfdorch.cpp",
    "icmporch.cpp",
    "srv6orch.cpp",
    "nvgreorch.cpp",
    "zmqorch.cpp",
    "dash/dashenifwdorch.cpp",
    "dash/dashenifwdinfo.cpp",
    "dash/dashcounter.cpp",
    "dash/dashorch.cpp",
    "dash/dashrouteorch.cpp",
    "dash/dashvnetorch.cpp",
    "dash/dashaclorch.cpp",
    "dash/dashaclgroupmgr.cpp",
    "dash/dashmeterorch.cpp",
    "dash/dashtagmgr.cpp",
    "dash/dashtunnelorch.cpp",
    "dash/pbutils.cpp",
    "dash/dashhaorch.cpp",
    "dash/dashhafloworch.cpp",
    "dash/dashportmaporch.cpp",
    "dash/dashresulthelper.cpp",
    "twamporch.cpp",
    "stporch.cpp",
    "nexthopkey.cpp",
    "macsecpost.cpp",
    "high_frequency_telemetry/hftelorch.cpp",
    "high_frequency_telemetry/hftelprofile.cpp",
    "high_frequency_telemetry/counternameupdater.cpp",
    "high_frequency_telemetry/hftelutils.cpp",
    "high_frequency_telemetry/hftelgroup.cpp",
    "shlorch.cpp",
    # flex_counter
    "flex_counter/flex_counter_manager.cpp",
    "flex_counter/flex_counter_stat_manager.cpp",
    "flex_counter/flow_counter_handler.cpp",
    "flex_counter/flowcounterrouteorch.cpp",
    # debug_counter
    "debug_counter/debug_counter.cpp",
    "debug_counter/drop_counter.cpp",
    # p4orch
    "p4orch/p4orch.cpp",
    "p4orch/p4orch_util.cpp",
    "p4orch/p4oidmapper.cpp",
    "p4orch/tables_definition_manager.cpp",
    "p4orch/router_interface_manager.cpp",
    "p4orch/gre_tunnel_manager.cpp",
    "p4orch/neighbor_manager.cpp",
    "p4orch/next_hop_manager.cpp",
    "p4orch/route_manager.cpp",
    "p4orch/acl_util.cpp",
    "p4orch/acl_table_manager.cpp",
    "p4orch/acl_rule_manager.cpp",
    "p4orch/wcmp_manager.cpp",
    "p4orch/mirror_session_manager.cpp",
    "p4orch/tunnel_decap_group_manager.cpp",
    "p4orch/l3_admit_manager.cpp",
    "p4orch/l3_multicast_manager.cpp",
    "p4orch/ip_multicast_manager.cpp",
    "p4orch/ext_tables_manager.cpp",
]

cc_binary(
    name = "orchagent",
    srcs = orchagent_SOURCES + glob(["**/*.h"]) + [
        "//fpmsyncd:fpmsyncd.h",
    ],
    cxxopts = CXX_COMMON + [
        "-std=c++17",
        "-Wno-write-strings",
        "-Wno-stack-protector",
        "-Wno-error=format=",
        "-Wno-error=overloaded-virtual",
        "-Wno-error=conversion",
        "-Wno-deprecated-declarations",
    ],
    dynamic_deps = [
        "@sonic_sairedis//lib:sairedis_shared",
        "@sonic_sairedis//meta:saimeta_shared",
        "@sai//meta:saimetadata_shared",
        "@sonic-swss-common//:swsscommon_shared",
        "@sonic_rules//protobuf:libprotobuf_shared",
        "@libnl3//:libnl_3_shared",
        "@libnl3//:libnl_nf_3_shared",
        "@libnl3//:libnl_route_3_shared",
        "@libyang3//:yang_shared",
    ],
    includes = [
        ".",
        "cbf",
        "debug_counter",
        "flex_counter",
        "high_frequency_telemetry",
        "nhg",
        "pbh",
        "port",
        "switch",
    ],
    deps = [
        ":orch_common",
        "//lib:libswss",
        "//warmrestart",
        "@libnl3//:libnl_3",
        "@libnl3//:libnl_route_3",
        "@protobuf//:protobuf",
        "@sonic-dash-api//:dashapi",
        "@sonic-dash-api//:dashapi_cpp_proto",
        "@sai//meta:saimetadata",
        "@sonic_sairedis//lib:sairedis",
        "@sonic_sairedis//meta:saimeta",
        "@sonic-swss-common//:swsscommon",
        "@swss_apt_deps//libzmq3-dev:libzmq3",
        "@swss_apt_deps//libjemalloc-dev:libjemalloc",
        "@swss_apt_deps//libyaml-cpp-dev:libyaml-cpp",
        "@sonic_rules//system_libs:pthread",
    ],
)

cc_binary(
    name = "routeresync",
    srcs = ["routeresync.cpp"] + glob(["*.h"]),
    cxxopts = CXX_COMMON,
    dynamic_deps = [
        "@sonic-swss-common//:swsscommon_shared",
        "@libnl3//:libnl_3_shared",
        "@libnl3//:libnl_nf_3_shared",
        "@libnl3//:libnl_route_3_shared",
        "@libyang3//:yang_shared",
    ],
    deps = [
        "//lib:libswss",
        "@sonic-swss-common//:swsscommon",
    ],
)

cc_binary(
    name = "orchagent_restart_check",
    srcs = ["orchagent_restart_check.cpp"],
    cxxopts = CXX_COMMON,
    dynamic_deps = [
        "@sonic-swss-common//:swsscommon_shared",
        "@libnl3//:libnl_3_shared",
        "@libnl3//:libnl_nf_3_shared",
        "@libnl3//:libnl_route_3_shared",
        "@libyang3//:yang_shared",
    ],
    deps = [
        "@sonic-swss-common//:swsscommon",
        "@swss_apt_deps//libhiredis-dev:libhiredis",
    ],
)

exports_files(["macsecpost.cpp"])
